after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders active_color=0xffd7f4ff inactive_color=0x00ffffff width=3.0',
]

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 100

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       3
outer.bottom =     3
outer.top =        [{monitor."built-in" = 5}, 38]
outer.right =      3

[mode.main.binding]

# All possible modifiers: cmd, alt, ctrl, shift
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -10'
alt-equal = 'resize smart +10'

alt-y = 'workspace Y'
alt-u = 'workspace U'
alt-i = 'workspace I'
alt-o = 'workspace O'
alt-p = 'workspace P'

alt-shift-y = 'move-node-to-workspace Y'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'

alt-f = 'layout floating tiling'
alt-shift-f = 'macos-native-fullscreen'
alt-d = 'macos-native-minimize'
alt-z = 'fullscreen --no-outer-gaps'
alt-r = 'flatten-workspace-tree'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-backtick = 'mode service'
alt-a = 'mode apps'

[mode.service.binding]
esc = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-h = ['join-with left', 'mode main']
alt-j = ['join-with down', 'mode main']
alt-k = ['join-with up', 'mode main']
alt-l = ['join-with right', 'mode main']

[mode.apps.binding]
esc = ['mode main']
t = ['exec-and-forget open -a /Applications/iTerm.app/', 'mode main']
s = ['exec-and-forget open -a /Applications/Safari.app/', 'mode main']
w = ['exec-and-forget open -a /Applications/WeChat.app/', 'mode main']
m = ['exec-and-forget open -a Mail', 'mode main']
f = ['exec-and-forget open /Users/jack/', 'mode main']

[[on-window-detected]]
check-further-callbacks = true
if.during-aerospace-startup = false
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
if.during-aerospace-startup = true
run = ['layout tiling', 'move-node-to-workspace O']

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.during-aerospace-startup = true
run = ['layout tiling', 'move-node-to-workspace O']
