#!/usr/bin/env bash

case "$1" in
  "com.apple.finder")
    ICON="󰀶"
    ;;
  "com.apple.Safari")
    ICON=""
    ;;
  "com.google.Chrome")
    ICON=""
    ;;
  "com.microsoft.edgemac")
    ICON=""
    ;;
  "com.apple.Terminal" | "com.googlecode.iterm2")
    ICON=""
    ;;
  "com.microsoft.VSCode")
    ICON="󰨞"
    ;;
  "us.zoom.xos")
    ICON=""
    ;;
  "com.tencent.xinWeChat")
    ICON=""
    ;;
  "com.apple.mail")
    ICON="󰇮"
    ;;
  "com.apple.Notes" | "md.obsidian")
    ICON=""
    ;;
  "com.micosoft.Word")
    ICON="󱎒"
    ;;
  "com.micosoft.Excel")
    ICON="󱎏"
    ;;
  "com.microsoft.Powerpoint")
    ICON="󱎐"
    ;;
  "com.apple.iCal")
    ICON=""
    ;;
  "com.apple.clock")
    ICON=""
    ;;
  "com.apple.calculator")
    ICON=""
    ;;
  "com.apple.SystemProfiler" | "com.apple.systempreferences")
    ICON=""
    ;;
  "com.apple.reminders")
    ICON=""
    ;;
  "com.apple.Passwords")
    ICON=""
    ;;
  "com.termius-dmg.mac")
    ICON="󰞶"
    ;;
  "com.apple.ScreenContinuity")
    ICON=""
    ;;
  "com.apple.MobileSMS")
    ICON=""
    ;;
  "com.apple.FaceTime")
    ICON=""
    ;;
  "com.apple.Photos")
    ICON=""
    ;;
  "com.openai.chat")
    ICON=""
    ;;
  "com.appel.weather")
    ICON=""
    ;;
  "com.apple.DiskUtility")
    ICON="󰨣"
    ;;
  "com.apple.Preview")
    ICON=""
    ;;
  "com.apple.PhotoBooth")
    ICON=""
    ;;
  "com.apple.Music")
    ICON=""
    ;;
  *)
    ICON="󰣆"
    ;;
esac

echo "$ICON"

